### ISSUE TITLE
Detection majuscule

### ISSUE THREAD

**Issue by ghost** [t2plb/MDP#2]
La tranche des chiffres est dans la tranche des majuscules
Une chiffre peut-être un chiffre et une majuscule en même temps ?

```c
if(ascii >= 41 && ascii <= 90){
    maj = maj + 1;
}
if(ascii >= 48 && ascii <= 59){
    chiffre = chiffre + 1;
}
```

Donc si je saisie le mdp : Irup1234
maj = 5 ( I , 1, 2, 3, 4)
chiffre = 4 (1, 2, 3, 4)

**Comment by t2plb** [comment]
Vu et corrigé
